on:
  workflow_dispatch:
    inputs:
      stand:
        description: 'Deploy static on AWS S3 (stage1/prod)'
        required: true
        default: 'stage1'

name: Deploy static on AWS S3

jobs:
  deploy-static:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/anyproto
      STAND: ${{ github.event.inputs.stand }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: git config
        run: git config --global url.https://${{ secrets.ANYTYPE_PAT }}@github.com/.insteadOf https://github.com/
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup GO env
        run: |
          echo GOPATH=$(go env GOPATH) >> $GITHUB_ENV
          echo GOBIN=$(go env GOPATH)/bin >> $GITHUB_ENV
          echo $(go env GOPATH)/bin >> $GITHUB_PATH
      - name: Setup license repository
        uses: actions/checkout@master
        with:
          repository: anyproto/open
          ref: refs/heads/main
          path: ./open
      - name: Go build
        run: |
          npm i
          make build
      - name: Debug
        run: |
          tree static/
      - name: Setup s3cmd (stage)
        if: github.event.inputs.stand == 'stage1'
        uses: s3-actions/s3cmd@v1.9.0
        with:
          access_key: ${{ secrets.STAGE_AWS_KEY_ID }}
          secret_key: ${{ secrets.STAGE_AWS_SECRET_ACCESS_KEY }}
          region: 'eu-central-1'
          provider: aws
      - name: Setup s3cmd (prod)
        if: github.event.inputs.stand == 'prod'
        uses: s3-actions/s3cmd@v1.9.0
        with:
          access_key: ${{ secrets.PROD_AWS_KEY_ID }}
          secret_key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          region: 'eu-central-2'
          provider: aws
      - name: Upload static on AWS S3
        run: |
          BUCKET_NAME="anytype-${{ env.STAND }}-publishserver"
          s3cmd sync --recursive ./static/ s3://$BUCKET_NAME/static/
          s3cmd info s3://$BUCKET_NAME/static/
