on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/anyproto
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: git config
        run: git config --global url.https://${{ secrets.ANYTYPE_PAT }}@github.com/.insteadOf https://github.com/
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          skip-cache: true
          version: latest
          only-new-issues: true
          args: --timeout 25m --verbose
